### ISSUE TITLE
acebviewer seems to be broken after Java update

### ISSUE THREAD

**Issue by chporter** [agmip/AcebViewer#1]
![capture](https://user-images.githubusercontent.com/320153/32955658-a1a1b3b6-cb84-11e7-9fa2-4c462371d440.JPG)

**Comment by MengZhang** [comment]
AgView-1.0-release-hf1 should fix this issue. It is already on the tools website.

**Comment by chporter** [comment]
OK, thanks! I should have looked on the tools site first!

**Comment by chporter** [comment]
This is ACEB viewer, not AgViewer! Is there an update for this one?
Thanks!

**Comment by chporter** [comment]
It's OK, if not - I can view the json. We can leave this ticket open until fixed.

**Comment by MengZhang** [comment]
I add 1.0.0-beta4 on the tools site. That should fix this issue.

**Comment by chporter** [comment]
Thanks!
